#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

function clone_repo {
	owner=$1
	name=$2
	sha=$3

	path=examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone "https://github.com/$owner/$name" "$path"
	fi

	pushd "$path" >/dev/null
	actual_sha=$(git rev-parse HEAD)
	if [ "$actual_sha" != "$sha" ]; then
		echo "Updating $owner/$name to $sha"
		git fetch
		git reset --hard "$sha"
	fi
	popd >/dev/null
}

clone_repo Azure bicep bb49a7aaa82f87ffee65e8053a44347d77f76ee1

known_failures="$(cat script/known_failures.txt)"

# Remove invalid directories
find examples -type d \( -name "InvalidCycles_CRLF" \
	-o -name "InvalidParameters_LF" -o -name "InvalidOutputs_CRLF" \
	-o -name "InvalidExpressions_LF" -o -name "InvalidDisableNextLineDiagnosticsDirective_CRLF" \
	-o -name "InvalidLambdas_LF" -o -name "InvalidLoadFunctions_CRLF" \
	-o -name "InvalidMetadata_CRLF" -o -name "InvalidModules_LF" \
	-o -name "InvalidMultilineString_CRLF" -o -name "InvalidNewlineSensitivity_LF" \
	-o -name "InvalidResources_CRLF" -o -name "InvalidTargetScopes_LF" \
	-o -name "InvalidTypeDeclarations_LF" -o -name "InvalidVariables_LF" \) \
	-exec rm -rf {} +

# shellcheck disable=2046
tree-sitter parse -q \
	"examples/**/*.bicep" \
	$(for failure in $known_failures; do echo "!${failure}"; done)

example_count=$(find examples -name "*.bicep" | wc -l)
failure_count=$(wc -w <<<"$known_failures")
success_count=$((example_count - failure_count))
success_percent=$(bc -l <<<"100*${success_count}/${example_count}")

printf \
	"Successfully parsed %d of %d example files (%.1f%%)\n" \
	"$success_count" "$example_count" "$success_percent"
